### ISSUE TITLE
feature for plugin

### ISSUE THREAD

**Issue by BrunoPeron** [chengpohi/elasticshell#12]
it would be interesting if, in addition to the possible connections such as aws, it was possible to open an ssh connection with some remote server that contains an elasticsearch service. Sorry for bad English

**Comment by chengpohi** [comment]
HI @BrunoPeron , Do you mean using ssh tunnel to connect Elasticsearch? I will achieve it in next version, Thanks your feedback 👍

**Comment by chengpohi** [comment]
Hi @BrunoPeron , ssh tunnel connection is supported in version 1.9.7, You can try [download from Jetbrains](https://plugins.jetbrains.com/files/16364/), If have met any problems, pls let me know.

![](https://plugins.jetbrains.com/files/16364/screenshot_a9428dfa-c995-4b5a-8add-d82a876cff3b)
