### ISSUE TITLE
option to disable cert validation 

### ISSUE THREAD

**Issue by UweW** [chengpohi/elasticshell#14]
There is no option to disable cert validation.
Specially in test/dev environments it can be a problem.
For example I fail to connect to the test instance :
Connect failed: Host name '192.168.250.2' does not match the certificate subject provided by the peer (CN=elasticsearch)

**Comment by chengpohi** [comment]
@UweW Got it, I will add this option in next version, and release in this week(with cheat sheet feature).

**Comment by chengpohi** [comment]
@UweW edql 1.9.9 released, default skip ssl verification, could you try and if any problems, pls let me know

https://github.com/chengpohi/edql/releases/tag/v1.9.9

**Comment by UweW** [comment]
I am not able to download and test, latest available for download is 1.9.8

**Comment by chengpohi** [comment]
Hi @UweW , Jetbrain is still reviewing the new version.  you try manual download edql plugin and install it or wait Jetbrain approve it.

https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/265120

**Comment by UweW** [comment]
I can confirm, it works after your update.
Thanks a lot
