### ISSUE TITLE
Connection fails with security exception

### ISSUE THREAD

**Issue by obp3ter** [chengpohi/elasticshell#25]
When trying to connect I get the following error in an HTML document as an error message: `This Elastic installation has strict security requirements enabled that your current browser does not meet.` I'm not exactly sure which setting does this, what might be relevant, is that we have `xpac.security.enabled=true` and `xpac.security.http.ssl.enabled=true`.

**Comment by chengpohi** [comment]
Hi @obp3ter , got it, I will try reproduce it and fix it in 1.9.21 version

**Comment by chengpohi** [comment]
Hi @obp3ter, seems you are using kibana proxy to connect Elasticsearch, could you try manually install version [v1.9.21](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/315809) and test connection?

and please set kibana host check box to use the kibana proxy connect Elasticsearch

![image](https://user-images.githubusercontent.com/5118048/230070821-e443d47b-e007-4ad3-90f2-12e96f12ad41.png)

**Comment by obp3ter** [comment]
It works now. Thank you.
