### ISSUE TITLE
AWS Signature Profile

### ISSUE THREAD

**Issue by uriofferup** [chengpohi/elasticshell#29]
Connecting to AWS OpenSearch Domains using AWS v4 Signature works as expected using the default profile.
But there is not option to choose/enter a different profile.

**Comment by chengpohi** [comment]
Hi @uriofferup  please try the latest version: [v1.9.30](https://github.com/chengpohi/edql/releases/tag/v1.9.30), and also you can download from Jetbrains market [v1.9.30](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/387551). and the default profile is **default**.

Thanks your feedback, If you meet any issue please let me know.

![image](https://github.com/chengpohi/edql/assets/5118048/0c761206-8b32-44e3-8ab2-b8dc4704537a)
