### ISSUE TITLE
Signing with AWS session credentials

### ISSUE THREAD

**Issue by arao** [chengpohi/elasticshell#3]
Hi Chengpohi,

First, great plugin. I'm using it and come across an issue where I need to access ES using credentials provided by stsAssume.

It has three parts 
aws_access_key_id
aws_secret_access_key
aws_session_token

First two can be entered by 
ApiKeyId
ApiKeySecret

but there is no way for entering session token.

As per AWS documentation, it can either be entered as a header 'X-Amz-Security-Token' or part of query string not both. https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

It would be great if this support can be added.

**Comment by chengpohi** [comment]
closed by: https://github.com/chengpohi/edql/issues/4
