### ISSUE TITLE
make json view as json editor

### ISSUE THREAD

**Issue by BMomani** [chengpohi/elasticshell#30]
in json view of the responce
![image](https://github.com/chengpohi/edql/assets/7019737/512786ce-edff-4558-8fe4-97ac9a7f26ad)

its good if it become editor(readonly) were we can benefit from the syntax highlight and expand/ collapse feature

**Comment by chengpohi** [comment]
Hi @BMomani  please try the latest version: [v1.9.30](https://github.com/chengpohi/edql/releases/tag/v1.9.30), and also you can download from Jetbrains market [v1.9.30](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/387551)

Thanks your feedback, If you meet any issue please let me know.


![image](https://github.com/chengpohi/edql/assets/5118048/041c84cb-2f68-413d-930f-548779fa5215)
![image](https://github.com/chengpohi/edql/assets/5118048/73dec0a7-e2af-4c38-8d70-f23a9b023bad)

**Comment by BMomani** [comment]
great work It wokred,
can you do the same thing for the properties 
in my case, I have a property that contains JSON object 
check how the rendering looks like right now when I expand the property value 

I know the possible values are endless but very common one is the JSON 
its even implemented in Datagrip as value viewer and editor 


![image](https://github.com/chengpohi/edql/assets/7019737/8843045d-4662-4ed7-9752-2b912d60ce33)

**Comment by chengpohi** [comment]
Hi @BMomani , Thanks your feedback, I have created a new issue #37 for follow this feature.
