### ISSUE TITLE
Allow selection of multiple index patterns 

### ISSUE THREAD

**Issue by bilak** [chengpohi/elasticshell#34]
In Kibana, it's possible to use following queries (note the commas)

`GET _cat/indices/*force*,*vehicle*,*duty*,*person*,*provider*?h=idx`
```
POST force*,vehicle*/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "terms": {
            "id": [
              "6afa60a0-3cf9-47b9-bf32-730b35d37b9a"
            ],
            "boost": 1.0
          }
        }
      ]
    }
  }
}
```

Would it be possible to use same syntax in this plugin? 
Thanks

**Comment by chengpohi** [comment]
Got it, I will try to achieve this pattern parser in next version release.

**Comment by chengpohi** [comment]
Hi @bilak  this feature is added to [v1.10.2](https://github.com/chengpohi/edql/releases/tag/v1.10.2), and also you can download from Jetbrains market [v1.10.2](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/445224).

Thanks your feedback, If you meet any issue please let me know.
