### ISSUE TITLE
[feature] Allow query execution by custom shortcut or align with Intellij

### ISSUE THREAD

**Issue by bilak** [chengpohi/elasticshell#36]
In other Intellij plugins (db, redis, ...) it's possible to execute the query by `cmd + enter`. Now it's little bit confusing to use shortcut `ctrl + shit + R`. Would it be possible to either align with Intellij shortcut or provide an option to use custom shortcut?

Thanks

**Comment by chengpohi** [comment]
Hi @bilak  this feature is added to [v1.10.2](https://github.com/chengpohi/edql/releases/tag/v1.10.2), and also you can download from Jetbrains market [v1.10.2](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/445224).

Thanks your feedback, If you meet any issue please let me know.
