### ISSUE TITLE
BUG: indices or aliases with a @ can't be queried

### ISSUE THREAD

**Issue by JeroenTriptic** [chengpohi/elasticshell#39]
I have indices with an @ in the name but I can't query them as I get this error:
![image](https://github.com/chengpohi/edql/assets/60502147/a37b649f-dcc1-4b6b-9a33-505641769cb2)

**Comment by chengpohi** [comment]
Hi @JeroenTriptic got it, for now the parser not support `@`, I will implement it in next release version, Thanks your feedback.

**Comment by chengpohi** [comment]
Hi @JeroenTriptic  please try the latest version: [v1.10.3](https://github.com/chengpohi/edql/releases/tag/v1.10.3), and also you can download from Jetbrains market [v1.10.3](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/457477)

Thanks your feedback, If you meet any issue please let me know.
