### ISSUE TITLE
Ability to sign using local AWS credential file.

### ISSUE THREAD

**Issue by arao** [chengpohi/elasticshell#4]
Associated with https://github.com/chengpohi/edql/issues/3

AWS also provide a way where session credentials are saved in ~/.aws/credentials . Configuration can also be specified in ~/.aws/config . There is way to distinguish between different profiles using name, default being 'default' . It would be great if plugin can automatically read the credentials, given profile name.

ref: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by chengpohi** [comment]
@arao Hello, Thanks your response, I will take look at this, I will add this feature in next in version 1.7.1. 

Also welcome other feedbacks

**Comment by chengpohi** [comment]
@arao the newest 1.7.1 version has released and add feature of aws credential connect, please check:

https://github.com/chengpohi/edql/wiki/EDQL:-Language-Specification#aws-iam-apikeyid-apikeysecret-and-apisessiontoken

**Comment by arao** [comment]
Thank you for you effort, it is working now.
