### ISSUE TITLE
bad show number with zero

### ISSUE THREAD

**Issue by mishin** [chengpohi/elasticshell#40]
I have value "type_id": "302.0",
for 
```java
    "type_id": {
      "type": "keyword"
    },

    @Field(name = "type_id", type = Keyword)
    private String typeId;
```
but view only "302"

**Comment by mishin** [comment]
![Screenshot 2024-01-12 at 19 55 52](https://github.com/chengpohi/edql/assets/2354218/c2246052-773a-484d-80db-7b2e0665ef6a)

**Comment by mishin** [comment]
query
```java
GET publ_post_entity/_search
{
  "query": {
    "bool": {
      "filter": {
        "term": {
          "uref.obj": "302"
        }
      }
    }
  }
}
```

**Comment by mishin** [comment]
in json view
```json
"_source": {
          "_class": "ru.nkt.search.service.entity.PublPostEntity",
          "id": "cf217626-37a3-4574-9124-df5ae05e2abe",
          "type_id": "302.0",
          "uref": {
            "obj": 302,
            "uuid": "cf217626-37a3-4574-9124-df5ae05e2abe",
            "asString": "302:cf217626-37a3-4574-9124-df5ae05e2abe",
            "type": "uref"
          },
```

**Comment by chengpohi** [comment]
Hi @mishin , got it , I will update the number display format issue in next version: 1.0.5, Thanks your feedback.

**Comment by chengpohi** [comment]
Hi @mishin  please try the latest version: [v1.10.5](https://github.com/chengpohi/edql/releases/tag/v1.10.5), and also you can download from Jetbrains market [v1.10.5](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/468640)

Thanks your feedback, If you meet any issue please let me know.
