### ISSUE TITLE
not able to configure connection

### ISSUE THREAD

**Issue by anish-diliyan** [chengpohi/elasticshell#42]

**Comment by chengpohi** [comment]
Hi @anish-diliyan , could you paste connection error info you met? which auth way you are using?  are you using proxy?

**Comment by anish-diliyan** [comment]
Actually their is an UI issue, I am not able see apply botton. So I am not
able to apply my configuration.
For now I have used the tab button and by assuming I am on apply button and
hit enter. Some how I am able to create connection.

**Comment by chengpohi** [comment]
Hi @anish-diliyan , Thanks your feedback, could you send a snapshot for this ui issue? maybe I can try to reproduce it.

**Comment by anish-diliyan** [comment]
Sure

**Comment by chengpohi** [comment]
Hi @anish-diliyan  please try the latest version: [v1.10.11](https://github.com/chengpohi/edql/releases/tag/v1.10.11), and also you can download from Jetbrains market [v1.10.11](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/559521)

Thanks your feedback, If you meet any issue please let me know.
