### ISSUE TITLE
[Autocompletion] Must, Must not, Should clause is not recognised for autocompletion.

### ISSUE THREAD

**Issue by arao** [chengpohi/elasticshell#5]
Hi chengpohi,

There is one issue I encountered while using this plugin. It does not recognised must, must_not, should clause for autocompletion. IDE give error until structure is completed.

Boolean query reference
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

**Comment by chengpohi** [comment]
Hi, Thanks your feedback,  this feature is  released by 1.7.2 version.

also in future will research a better autocompletion for Elasticsearch Query DSL, for my idea, it's hard to use with JSON

https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions

**Comment by chengpohi** [comment]
https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions
