### ISSUE TITLE
Connection issues against Opensearch

### ISSUE THREAD

**Issue by coyotesqrl** [chengpohi/elasticshell#50]
**Describe the bug**
We are migrating from Elasticsearch to Opensearch and when I try to configure a connection to the Opensearch url with username/password, I get an `Authentication finally failed` response.

I've confirmed my credentials by querying through cURL and Postman, so this seems to be something specific to the plugin.

It is of course possible that this is not a bug, that the plugin ONLY works with Elasticsearch and not Opensearch; however, I've seen some mentions of the latter in other Issues as I searched for my problem.

...

**To Reproduce**
1. Go to create a connection
2. Set the Host to a valid Opensearch URL
3. Select the `Username & Password` auth option
4. Enter valid credentials
5. Press either `Test` or `Apply`

**Expected behavior**
A working connection.

**Screenshots**

**Comment by chengpohi** [comment]
Hi @coyotesqrl , Thanks your feedback, I will try to reproduce this issue, and fix it in next version

**Comment by chengpohi** [comment]
Hi @coyotesqrl , Could you try version 1.0.18, download from Jetbrains market [v1.10.18](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/647011) or manual install by [Github release v1.10.18](https://github.com/chengpohi/edql/releases/tag/v1.10.18).

and use the opensearch dashboad proxy(select Kibana Host Proxy option) to connect your opensearch:

<img width="575" alt="image" src="https://github.com/user-attachments/assets/026eac8f-1386-48ef-9087-6de5b37c0024">

I have tested in newst opensearch version it works,  if you still meet issue, please paste opensearch version and security info.

Thanks your feedback

**Comment by coyotesqrl** [comment]
> Hi @coyotesqrl , Could you try version 1.0.18, download from Jetbrains market [v1.10.18](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/647011) or manual install by [Github release v1.10.18](https://github.com/chengpohi/edql/releases/tag/v1.10.18).
> 
> and use the opensearch dashboad proxy(select Kibana Host Proxy option) to connect your opensearch:
> 
> <img alt="image" width="575" src="https://private-user-images.githubusercontent.com/5118048/393886194-026eac8f-1386-48ef-9087-6de5b37c0024.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTcyNjUsIm5iZiI6MTczMzc1Njk2NSwicGF0aCI6Ii81MTE4MDQ4LzM5Mzg4NjE5NC0wMjZlYWM4Zi0xMzg2LTQ4ZWYtOTA4Ny02ZGU1YjM3YzAwMjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMTUwOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2RlYmNiMTI4YjJhZjkxYzZlOTBjOTBlOWE5NTQ1YTJiNjVkNGQ1M2U2M2Y0MGEzNWQ4YTY1Y2IxYzI4ZTY3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MJZhSJqSrH5zMo5FDVn4Fn-tfDizG3dHoHKXrPRf-m8">
> I have tested in newst opensearch version it works, if you still meet issue, please paste opensearch version and security info.
> 
> Thanks your feedback

I'm not exactly clear what I'm supposed to be using for my connection. Is there some local proxy I'm supposed to be running to connect to my AWS opensearch instances? That was not the case previously.

**Comment by chengpohi** [comment]
@coyotesqrl can you let me know your opensearch version?

**Comment by chengpohi** [comment]
**Kibana host proxy** means that if you can't directly connect Elasticsearch/Opensearch, but you can visit Kibana/Opensearch dashboard, you can use Kibana/Opensearch dashboard url(ex: http://localhost:5601), and selected **Kibana host proxy**, this method will visit Elasticsearch/Opensearch host by through Dashboard proxy

**Comment by coyotesqrl** [comment]
Thanks. Using the AWS proxy resolved it. The issue is complete as far as I'm concerned.
