### ISSUE TITLE
EDQL Visual Editor not support Username and Password ?

### ISSUE THREAD

**Issue by huangyuan1113** [chengpohi/elasticshell#7]
EDQL Visual Editor not support Username and Password ?

**Comment by chengpohi** [comment]
Yes, I will try to explore new interactive for authorization, maybe in version 1.7.4 in next week.

Visual Editor is still experimental, since Elasticsearch DSL is complex, need more thoughts for visual interactions.

Also I am exploring visualization display the aggs result for analysis.

**Comment by chengpohi** [comment]
![image](https://user-images.githubusercontent.com/5118048/154801605-cbfafe0d-efc4-4b74-810e-b7634df49d56.png)
https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions
1.74. released for support multi auth visualizations. 

Thanks your feedback.
