### ISSUE TITLE
EDQL side window: copy to clipboard doesn't work

### ISSUE THREAD

**Issue by lubino** [chengpohi/elasticshell#8]
Copy and Paste (clipboard functions) are not working in EDQL side window. Name of index or alias is not stored in Clipboard after pressing Cmd+C (Ctrl+C). Also not available in Context menu.

<img width="251" alt="Screenshot 2022-05-11 at 12 39 15" src="https://user-images.githubusercontent.com/542898/167831531-24508ba4-e2aa-4f6f-8ffe-c019d5bb5da6.png">

Is this basic feature broken or just not implemented?

**Comment by chengpohi** [comment]
@lubino it's not implemented, side window is still refactoring to explore a better way to display Elasticsearch hosts, scripts and console.  Thanks your feedback :)

I will publish a newer version in next week for support copy index and alias.

**Comment by lubino** [comment]
Thank you @chengpohi for creating this useful plugin and also for addressing this issue. 
I am looking forward to try out future versions.

**Comment by chengpohi** [comment]
@lubino Hi lubino, the newer version EDQL: 1.8.2 has released, empower EDQL Dock Manager: 
- copy index, host name etc
- double click for index query, node info, template info etc
- right click for more functions: new index, reindex, import data to index etc
- fix some issues of edql syntax, tool window issues

https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/175144
