### ISSUE TITLE
大佬，提交的时候出现下面的错误

### ISSUE THREAD

**Issue by hekensway** [chengpohi/elasticshell#9]
![image](https://user-images.githubusercontent.com/18020016/169734465-38e878b4-2419-4544-a80b-4eb3ae101198.png)

咋回事啊，这个是

**Comment by chengpohi** [comment]
@hekensway I will take look at this.

**Comment by chengpohi** [comment]
@hekensway It this document id include unicode chars?

**Comment by chengpohi** [comment]
Hi @hekensway this issue is caused by version 1.8.2, I have fixed it 1.8.3 version, you can download and install from(IDE push notification has some latency):

https://plugins.jetbrains.com/files/16364/178154/edql-plugin-1.8.3.zip

https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions

also this version has support chart display, have fun.

![](https://chengpohi.github.io/.gitbook/assets/display-chart.gif)

**Comment by hekensway** [comment]
> Hi @hekensway this issue is caused by version 1.8.2, I have fixed it 1.8.3 version, you can download and install from(IDE push notification has some latency):
> 
> https://plugins.jetbrains.com/files/16364/177747/edql-plugin-1.8.3.zip https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions
> 
> also this version has support chart display, have fun.
> 
> ![](https://camo.githubusercontent.com/5662a2a0e79f7eae3c39c718d14aae86d8e2c70514b01f592dbe6dd669670670/68747470733a2f2f6368656e67706f68692e6769746875622e696f2f2e676974626f6f6b2f6173736574732f646973706c61792d63686172742e676966) [ ](https://camo.githubusercontent.com/5662a2a0e79f7eae3c39c718d14aae86d8e2c70514b01f592dbe6dd669670670/68747470733a2f2f6368656e67706f68692e6769746875622e696f2f2e676974626f6f6b2f6173736574732f646973706c61792d63686172742e676966) ![68747470733a2f2f6368656e67706f68692e6769746875622e696f2f2e676974626f6f6b2f6173736574732f646973706c61792d63686172742e676966](https://camo.githubusercontent.com/5662a2a0e79f7eae3c39c718d14aae86d8e2c70514b01f592dbe6dd669670670/68747470733a2f2f6368656e67706f68692e6769746875622e696f2f2e676974626f6f6b2f6173736574732f646973706c61792d63686172742e676966) [ ](https://camo.githubusercontent.com/5662a2a0e79f7eae3c39c718d14aae86d8e2c70514b01f592dbe6dd669670670/68747470733a2f2f6368656e67706f68692e6769746875622e696f2f2e676974626f6f6b2f6173736574732f646973706c61792d63686172742e676966)

thank you!

**Comment by hekensway** [comment]
![image](https://user-images.githubusercontent.com/18020016/170435980-753e4b8e-8669-4505-b66a-710a3a674580.png)
it's report this error 

on windows7  
![image](https://user-images.githubusercontent.com/18020016/170436249-caf614df-bd7b-474b-8e39-4cf790c00d1c.png)
渲染不出来

**Comment by chengpohi** [comment]
Hi @hekensway thanks your feedback, the download link is broken.

Could you try download this: https://plugins.jetbrains.com/files/16364/178144/edql-plugin-1.8.3.zip

or wait intellij notifaction for update plugin

**Comment by chengpohi** [comment]
Hi @hekensway thanks your feedback, the uploaded zip is broken, you can try this: 
https://plugins.jetbrains.com/files/16364/178158/edql-plugin-1.8.3.zip

or wait intellij notification push

**Comment by hekensway** [comment]
> Hi @hekensway thanks your feedback, the uploaded zip is broken, you can try this: https://plugins.jetbrains.com/files/16364/178158/edql-plugin-1.8.3.zip
> 
> or wait intellij notification push

thank you.  My problem has  solved.
